### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by fakename131** [ItsTobez/Discord-Bot#1]

**Comment by tobyab** [comment]
I really appreciate your concerns about me and my age.

**Comment by andrewn6** [comment]
> ur 12 lol
> 
> > "you agree (i) that you are 13 years of age and the minimum age of digital consent in your country, (ii) if you are the age of majority in your jurisdiction or over, that you have read, understood, and accept to be bound by the Terms, and (iii) if you are between 13 (or the minimum age of digital consent, as applicable) and the age of majority in your jurisdiction, that your legal guardian has reviewed and agrees to these Terms."

stop witch hunting people on github for their age, no one cares..
